import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "About Us | Invoy – Dissolve IT",
  description: "We're a team of builders and freelancers based in Boston, MA, building the AI payment guardian for independent contributors.",
};

export default function AboutPage() {
  return (
    <>
      <Navbar />
      <main>
        {/* Hero */}
        <section className="bg-navy py-24 px-4">
          <div className="max-w-2xl mx-auto text-center">
            <span className="inline-block bg-white/10 text-white/60 text-xs font-semibold px-3 py-1.5 rounded-full mb-6">
              About Us
            </span>
            <h1 className="text-white text-4xl sm:text-5xl font-bold leading-tight mb-5">
              About Us — Coming Soon
            </h1>
            <p className="text-white/60 text-lg leading-relaxed mb-9">
              We&apos;re a team of builders, freelancers, and finance nerds based in
              Boston, MA. Our full story is coming soon — but our mission is
              simple: make sure great work gets paid fairly and on time.
            </p>
            <Link
              href="/contact-us"
              className="inline-block bg-mint text-navy font-bold px-8 py-3.5 rounded-full hover:bg-mint/90 transition-colors text-sm"
            >
              Get early access
            </Link>
          </div>
        </section>

        {/* Values */}
        <section className="bg-light-blue py-16 px-4">
          <div className="max-w-4xl mx-auto grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div className="bg-white rounded-2xl p-7 border border-gray-100">
              <div className="w-10 h-10 bg-light-purple rounded-xl flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-purple" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <h3 className="text-navy font-bold text-lg mb-2">Our Mission</h3>
              <p className="text-gray-text text-sm leading-relaxed">
                To make financial freedom accessible for every independent
                contributor. We believe great work deserves to be paid fairly
                and on time — always.
              </p>
            </div>

            <div className="bg-white rounded-2xl p-7 border border-gray-100">
              <div className="w-10 h-10 bg-light-mint rounded-xl flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-navy" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </div>
              <h3 className="text-navy font-bold text-lg mb-2">Our Team</h3>
              <p className="text-gray-text text-sm leading-relaxed">
                Former freelancers and consultants who felt the pain firsthand.
                We&apos;re building Invoy so no one else has to chase down
                their own money.
              </p>
            </div>

            <div className="bg-white rounded-2xl p-7 border border-gray-100">
              <div className="w-10 h-10 bg-light-purple rounded-xl flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-purple" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                </svg>
              </div>
              <h3 className="text-navy font-bold text-lg mb-2">Our Promise</h3>
              <p className="text-gray-text text-sm leading-relaxed">
                99% payment accuracy, every time. We stand behind every
                invoice generated by Invoy. If you don&apos;t get paid,
                neither do we.
              </p>
            </div>

            <div className="bg-white rounded-2xl p-7 border border-gray-100">
              <div className="w-10 h-10 bg-light-mint rounded-xl flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-navy" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </div>
              <h3 className="text-navy font-bold text-lg mb-2">Based in Boston</h3>
              <p className="text-gray-text text-sm leading-relaxed">
                We&apos;re proudly headquartered in Boston, MA — built in the
                heart of one of America&apos;s most vibrant tech and startup
                ecosystems.
              </p>
            </div>
          </div>
        </section>

        {/* Contact CTA */}
        <section className="bg-white py-16 px-4 text-center">
          <div className="max-w-xl mx-auto">
            <h2 className="text-navy text-2xl font-bold mb-3">Want to know more?</h2>
            <p className="text-gray-text mb-6 text-sm leading-relaxed">
              Reach out directly or join the early access waitlist. We read every message.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <a
                href="mailto:team@dissolveit.ai"
                className="border-2 border-navy/15 text-navy font-semibold px-7 py-3 rounded-full hover:border-navy/30 transition-colors text-sm"
              >
                team@dissolveit.ai
              </a>
              <Link
                href="/contact-us"
                className="bg-purple text-white font-semibold px-7 py-3 rounded-full hover:bg-purple/90 transition-colors text-sm"
              >
                Join the waitlist
              </Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
